language: python
python:
- 3.6.0
services:
- docker
install:
- pip install -r context/python/requirements.txt
script:
- "./test.sh"
after_success:
- "./after_success.sh"
env:
  global:
    secure: bVuV6gtz7GWdQ58aJsTm9KBmXnHLM3l7ZK+ZbvGf8VdsXtFOugtfsl9s/H8mwc68pzMgmFU4it04d5zoqxctiGybQWLH81ylgL4GjKzokTjDhdFiy4KZNa5mxeudwWNZ/v/KCd59yotjtGhtNDgV5cDvf9DolPpu9D6cunZPF2FNPTu7en0noTMcEhVBJJHp3EbUd/7t72BMsV8Ya0UKnAGorynqFNy4qDWa4oJZHlWK9rIkR4sDLDlQjivMnQUGLEf30qu6XTL01YuyDwmUQSYQCSQTuedKfnZxxthInIjsjQ14YvVh6pAtZ4MnCT+iwo8iCdM3zYScX2SUT0tSYny/LNVbsWK52AGRRtG35R57XA8ywftWunXnUDlPWIvtJMcjXdSMU6V7OVjHVsI+/r81aWFFUP3oAfT2zQtrHko/bI4ssyEi21T7V252aySJmzgETEmmahJH3prGWILz5eQxzWsZWU0B0WpHZ4ZhJU84Y90sWt1rxnlx+MkuI3hzUp9sY6ba6tr02PeE37xFODQJUzhNbfUOVFBAxdu+LuEzqMvNSoLTxJPvkwpoWtymvFqyXyzdFMsyz/u4to5fI5XdBas+nbjn8uKybAhuuujexgHy89oe02pMshFE7LqX7sWkH+rgPa7M++t2V6/lcAf+4ZwZZnJs1hRtUCjAIKE=
